#ifndef REFLECT_CONFIG_PLATFORM_GENERIC_H_
#define REFLECT_CONFIG_PLATFORM_GENERIC_H_

#ifndef REFLECT_EXPORT_ANNOTATION
# define REFLECT_EXPORT_ANNOTATION
#endif

#ifndef REFLECT_IMPORT_ANNOTATION
# define REFLECT_IMPORT_ANNOTATION
#endif

#endif
